#shell executor pipeline
stages:
  - prepare & code scan
  - maven-build

build-tag-version:
  stage: prepare & code scan
  needs: []
  tags:
    - docker-runner
  script: 
    - POM_VERSION=$(mvn --non-recursive help:evaluate -Dexpression=project.version -q -DforceStdout)
    - ARTIFACT_ID=$(mvn --non-recursive help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
    - VERSION=${POM_VERSION}-$CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA
    - echo "Version - $VERSION"
    - echo "VERSION=$VERSION" >> build.env
    - echo "ARTIFACT_ID=$ARTIFACT_ID" >> build.env  
  artifacts:
    reports:
      dotenv: build.env

maven-build:
  stage: maven-build
  dependencies:
    - build-tag-version
  needs: [build-tag-version]
  tags:
    - docker-runner   
  script: 
    - |
      mvn dependency:go-offline
      mvn versions:set -DnewVersion=$VERSION
      mvn -DskipTests clean package        
  artifacts:
    paths:
      - target/*.jar