server:
  port: 8888
  servlet:
    contextPath: /template
  jackson:
    date-format: yyyy-MM-dd
spring:
  jackson:
    parser:
      allow-backslash-escaping-any-character: true
# --------------------------------------------------
# swagger / openapi config
# --------------------------------------------------
springdoc:
  packagesToScan: com.mutu.spring
  api-docs.path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
appInfo:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  license.name: 'Mutu'
  license.url: 'http://mutu.nocontact.com'

# --------------------------------------------------
# CORS Config
# --------------------------------------------------
cors:
  headers:
    - "X-XSS-Protection: 1"
    - "X-Content-Type-Options: nosniff"
    - "Cache-Control: no-cache, no-store, max-age=0, must-revalidate"
    - "Pragma: no-cache"
    - "Expires: 0"
    - "X-Frame-Options: SAMEORIGIN"
    - "Content-Security-Policy: script-src 'self'"
    - "Vary: Origin"
    - "Access-Control-Allow-Origin: *"
    - "Access-Control-Allow-Credentials: true"
    - "Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS"
    - "Access-Control-Allow-Headers: Authorization,Access-Control-Allow-Origin,Content-Type,User-Account,sessionID,X-XSS-Protection,X-Content-Type-Options,Cache-Control,Pragma,Expires,X-Frame-Options,Content-Security-Policy"
    - "Access-Control-Expose-Headers: Authorization,Content-Disposition"
# --------------------------------------------------
# log4j2 + ELK
# --------------------------------------------------
header-key-list:
  log4jThreadContextList: x-root-correlation-id
componentLoggerEnabled: false  

# ------------------------------------------------------------------------------------------
# HTTPS using Self-Signed Certificate
#
# keytool -genkeypair -alias mutu -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore D:/mutu.p12 -validity 3650 <-- generate Self-Signed Certificate (CA ROOT)
#
# keytool -export -keystore D:/mutu.p12 -alias mutu -file D:/local-cert.crt -validity 3650 <-- generate certificate
# ------------------------------------------------------------------------------------------
server.ssl:
  enabled: true
  key-store-type: PKCS12
  key-store: classpath:keystore/mutu.p12
  key-store-password: 123456
  key-alias: mutu