management.endpoints.web.exposure.include: "*"
management.endpoints.web.exposure.exclude: "threaddump,heapdump"
management.metrics.tags.application: ${spring.application.name}
management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true
server:
  port: 8080
  servlet:
    contextPath: /demo
  lifecycle:
    timeout-per-shutdown-phase: "60s"
  tomcat:
    threads.max: 500
spring:
  application:
    name: springboot-demo