management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true

server:
  port: 8888
  servlet:
    contextPath: /demo
  jackson:
    date-format: yyyy-MM-dd

spring.main.allow-bean-definition-overriding: true
spring.h2.console.enabled: true

# --------------------------------------------------
# Database config
# --------------------------------------------------
database:
  primary:
    r2dbc:
      url: r2dbc:pool:postgresql://localhost:26257/devtest?sslmode=disable
      username: devuser
      password:
    r2dbc.pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      max-create-connection-time: 5s
      validation-query: SELECT 1        

# --------------------------------------------------
# Oauth 2, security config
# --------------------------------------------------
spring.security.enabled: true
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://127.0.0.1:8080/oauth2/jwks

# --------------------------------------------------
# CORS Config
# --------------------------------------------------
corsConfig:
  allow-origin: http://localhost:3000,https://myapp.com
  allow-credentials: false 
  allow-methods: GET,POST
  allow-headers: Authorization,Access-Control-Allow-Origin,Content-Type,User-Account,sessionID,X-XSS-Protection,X-Content-Type-Options,Cache-Control,Pragma,Expires,X-Frame-Options,Content-Security-Policy
  expose-headers: Authorization,Content-Disposition
# --------------------------------------------------
# swagger / openapi config
# --------------------------------------------------
springdoc:
  packagesToScan: org.mutu.example.api
  enable-native-support: true
  api-docs.path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
appInfo:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  license.name: 'Springboot Teamplate Project by Mutu'
  license.url: 'http://mutu.nocontact.com'
  
header-key-list:
  log4jThreadContextList: x-root-id, initrator  