CREATE SEQUENCE EMPLOYEE_SEQ START WITH 7 INCREMENT BY 1 ;

CREATE TABLE EMPLOYEE ( 
   ID INT PRIMARY KEY, 
   NAME VARCHAR(50) NOT NULL, 
   DEPARTMENT VARCHAR(50) NOT NULL
);

INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT) VALUES (1, 'Mutu', 'IT');
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT) VALUES (2, 'Jone', 'HR');
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT) VALUES (3, 'Smith', 'Sale');
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT) VALUES (4, 'Mice', 'Operation');
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT) VALUES (5, 'Rose', 'IT');
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT) VALUES (6, 'Bashi', 'EA');
