CREATE SEQUENCE DEPARTMENT_SEQ START WITH 3 INCREMENT BY 1 ;

CREATE TABLE DEPARTMENT ( 
   ID INT PRIMARY KEY, 
   NAME VARCHAR(50) NOT NULL 
);

INSERT INTO DEPARTMENT (ID, NAME) VALUES (1, 'IT');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (2, 'HR');
