CREATE SEQUENCE EMPLOYEE_SEQ START WITH 7 INCREMENT BY 1 ;

CREATE TABLE EMPLOYEE ( 
   ID INT PRIMARY KEY, 
   NAME VARCHAR(50) NOT NULL, 
   AGE INT NOT NULL,
   DEPARTMENT VARCHAR(50) NOT NULL
);

INSERT INTO EMPLOYEE (ID, NAME, AGE, DEPARTMENT) VALUES (1, 'Mutu', 37,'IT');
INSERT INTO EMPLOYEE (ID, NAME, AGE, DEPARTMENT) VALUES (2, 'Jone', 25, 'HR');
INSERT INTO EMPLOYEE (ID, NAME, AGE, DEPARTMENT) VALUES (3, 'Smith', 45, 'Sale');
INSERT INTO EMPLOYEE (ID, NAME, AGE, DEPARTMENT) VALUES (4, 'Mice', 54, 'Operation');
INSERT INTO EMPLOYEE (ID, NAME, AGE, DEPARTMENT) VALUES (5, 'Rose', 19, 'IT');
INSERT INTO EMPLOYEE (ID, NAME, AGE, DEPARTMENT) VALUES (6, 'Bashi', 24, 'EA');
