DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
   EMP_NO VARCHAR(255) NOT NULL, 
   FIRST_NAME VARCHAR(255) NOT NULL, 
   LAST_NAME VARCHAR(255) NOT NULL,
   DOB DATE NOT NULL,
   EMAIL VARCHAR(255) NOT NULL,
   PRIMARY KEY(EMP_NO)
);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_EMAIL_UNIQUE UNIQUE(EMAIL);

INSERT INTO EMPLOYEE(EMP_NO, FIRST_NAME, LAST_NAME, DOB, EMAIL) VALUES('JP0001', 'Zaw', 'Than Oo', DATE'1986-08-24','mutu@gmail.com');

