# spring:
#   datasource:
#     password: <path:secret/data/tls/apitest#password>
#     username: <path:secret/data/tls/apitest#username>
employee:
  datasource:
    jdbcUrl: jdbc:h2:mem:employeedb
    username: sa
    password: password
department:
  datasource:
    jdbcUrl: jdbc:h2:mem:departmentdb
    username: sa
    password: password    