# employee:
#   datasource:
#     password: <path:secret/data/tls/apitest#password>
#     username: <path:secret/data/tls/apitest#username>
employee:
  datasource:
    username: sa
    password: password
department:
  datasource:
    username: sa
    password: password    