# spring:
#   datasource:
#     password: <path:secret/data/tls/apitest#password>
#     username: <path:secret/data/tls/apitest#username>
spring:
  datasource:
    username: sa
    password: password
